INSERT INTO doctors (name, specialization, description, fee, email, password) VALUES
('Dr. Emily Carter', 'Cardiology', 'Specializing in heart disease diagnosis and treatment. Provides comprehensive cardiovascular care.', 250.00, 'emily.carter@hospital.com', 'HASHED_PASSWORD_1'),
('Dr. James Peterson', 'Neurology', 'Expert in treating disorders of the nervous system, including stroke and epilepsy.', 300.00, 'james.peterson@hospital.com', 'HASHED_PASSWORD_2'),
('Dr. Sarah Chen', 'Dermatology', 'Focuses on skin conditions, offering cosmetic and medical treatments for all ages.', 180.00, 'sarah.chen@hospital.com', 'HASHED_PASSWORD_3'),
('Dr. David Lee', 'Pediatrics', 'Dedicated to the health and well-being of infants, children, and adolescents.', 200.00, 'david.lee@hospital.com', 'HASHED_PASSWORD_4'),
('Dr. Maria Rodriguez', 'Oncology', 'Provides compassionate care and advanced treatment options for cancer patients.', 450.00, 'maria.rodriguez@hospital.com', 'HASHED_PASSWORD_5'),
('Dr. Michael Brown', 'Orthopedics', 'Specializes in musculoskeletal system injuries and conditions, including joint replacement.', 320.00, 'michael.brown@hospital.com', 'HASHED_PASSWORD_6'),
('Dr. Jessica Taylor', 'Gastroenterology', 'Treats diseases of the digestive system, from ulcers to inflammatory bowel disease.', 280.00, 'jessica.taylor@hospital.com', 'HASHED_PASSWORD_7'),
('Dr. Robert Green', 'Psychiatry', 'Helps patients manage mental health disorders and emotional challenges.', 220.00, 'robert.green@hospital.com', 'HASHED_PASSWORD_8'),
('Dr. Laura Wilson', 'Endocrinology', 'Manages hormonal imbalances and conditions like diabetes and thyroid disorders.', 290.00, 'laura.wilson@hospital.com', 'HASHED_PASSWORD_9'),
('Dr. Steven King', 'Urology', 'Focuses on the urinary tract system and male reproductive organs.', 270.00, 'steven.king@hospital.com', 'HASHED_PASSWORD_10'),
('Dr. Olivia Davis', 'Ophthalmology', 'Specializing in eye and vision care, including surgery and disease management.', 260.00, 'olivia.davis@hospital.com', 'HASHED_PASSWORD_11'),
('Dr. Daniel Adams', 'Pulmonology', 'Treats conditions affecting the respiratory system, such as asthma and COPD.', 310.00, 'daniel.adams@hospital.com', 'HASHED_PASSWORD_12'),
('Dr. Chloe Wilson', 'Gynecology', 'Provides comprehensive healthcare for women, with a focus on reproductive health.', 240.00, 'chloe.wilson@hospital.com', 'HASHED_PASSWORD_13'),
('Dr. Ethan Parker', 'Nephrology', 'Expert in kidney care and the treatment of kidney diseases.', 330.00, 'ethan.parker@hospital.com', 'HASHED_PASSWORD_14'),
('Dr. Sophia Miller', 'Rheumatology', 'Specializes in the diagnosis and treatment of diseases of the joints, muscles, and bones.', 275.00, 'sophia.miller@hospital.com', 'HASHED_PASSWORD_15'),
('Dr. Noah Garcia', 'Infectious Disease', 'Focuses on diagnosing and treating complex infections.', 350.00, 'noah.garcia@hospital.com', 'HASHED_PASSWORD_16'),
('Dr. Mia Robinson', 'Anesthesiology', 'Provides anesthesia for surgical procedures and pain management.', 400.00, 'mia.robinson@hospital.com', 'HASHED_PASSWORD_17'),
('Dr. Liam Turner', 'Allergy & Immunology', 'Helps patients manage allergies and immune system disorders.', 210.00, 'liam.turner@hospital.com', 'HASHED_PASSWORD_18'),
('Dr. Ava Hill', 'General Surgery', 'Performs a wide range of surgical procedures.', 380.00, 'ava.hill@hospital.com', 'HASHED_PASSWORD_19'),
('Dr. Jacob Wright', 'Radiology', 'Interprets medical images to diagnose injuries and diseases.', 315.00, 'jacob.wright@hospital.com', 'HASHED_PASSWORD_20');